apiVersion: v1
kind: Secret
metadata:
  name: rclone-config
type: Opaque
data:
  rclone.conf: |
    [backup] # Backup is the name of the remote that will be used in the rclone command
    # See https://rclone.org/overview/ for more info
    type = drive
    client_id = YOUR_CLIENT_ID
    client_secret = YOUR_CLIENT_SECRET
    scope = drive
    token = YOUR_TOKEN
