apiVersion: v1
kind: Secret
metadata:
  name: job-backup-mariadb-secret
type: Opaque
data:
  MC_HOST_s3: dGVzdA==
  BAGCLI_DATABASE_PASS: dGVzdA==
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: job-backup-mariadb
spec:
  concurrencyPolicy: Forbid
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  suspend: false
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          containers:
          - image: skyloud/job-backup-db:0.1.12
            args:
              - mariadb
              - mariadb_d_test
            envFrom:
            - secretRef:
                name: job-backup-mariadb-secret
                optional: false
            env:
              - name: BAGCLI_RETENTION_TIME
                value: 3d
              - name: BAGCLI_DATABASE_HOST
                value: host
              - name: BAGCLI_DATABASE_USER
                value: database_name
              - name: BAGCLI_DATABASE_PORT
                value: "3306"
              - name: BAGCLI_REMOTE_PATH
                value: bucket/databases/mariadb/test
              - name: TZ
                value: Europe/Paris
              - name: BAGCLI_HEARTBEAT_URL
                value: X
            volumeMounts:
            - mountPath: /home/job/.config/rclone
              name: rclone
            imagePullPolicy: Always
            name: database-backup
          tolerations: []
          volumes:
          - name: rclone
            secret:
              secretName: rclone-config
              items:
              - key: rclone.conf
                path: rclone.conf